/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.example;

import com.speedment.jpastreamer.application.JPAStreamer;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;

import static org.junit.jupiter.api.Assertions.*;


@SpringBootTest
class AppTest {

    @Autowired
    JPAStreamer jpaStreamer;

    @Test void japStreamerReady() {
        assertNotNull(jpaStreamer);

    }
}
