/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.example;

import com.example.domain.Film;
import com.speedment.jpastreamer.application.JPAStreamer;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        JPAStreamer jpaStreamer = JPAStreamer.of("app");

        jpaStreamer.stream(Film.class)
                .forEach(System.out::println);
        jpaStreamer.close();
    }
}
