/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.example;

import com.example.domain.Film;
import com.example.domain.Film$;
import com.speedment.jpastreamer.application.JPAStreamer;
import org.springframework.boot.CommandLineRunner;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.annotation.Bean;

import java.util.List;
import java.util.stream.Collectors;

@SpringBootApplication
public class App {
    public static void main(String[] args) {
        SpringApplication.run(App.class);
    }

    @Bean
    CommandLineRunner commandLineRunner(final JPAStreamer jpaStreamer) {
        return args -> {
            List<String> list = jpaStreamer.stream(Film.class)
                    .filter(Film$.title.startsWith("A"))
                    .map(Film::getTitle)  // Not affect SQL, ouch!
                    .collect(Collectors.toList());
            System.out.println(list);
        };
    }
}
